project:
  type: book

book:
  title: "R Data Science Note"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/r-ds
  site-url: https://r-ds-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Clean Data"
      chapters:
        - "clean/date/clean-date.qmd"
    - part: "Summary"
      chapters:
        - "summary/gtsum-sum.qmd"
    - part: "Statistic"
      chapters:
        - "stat/prop-compare.qmd"

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 4
    code-fold: show


execute:
  freeze: auto
